.TH irtestcase "1" "Last change: March 2009" "irtestcase @version@" "User Commands"
.SH NAME
irtestcase - create or check decoding testcases.
.SH SYNOPSIS
.B irtestcase [-l lircrc-file -p prog] <socket>
.br
.B irtestcase [-l lircrc-file -p prog] -t testdata <socket>
.br
.B irtestcase [-v|-h|

.SH DESCRIPTION
irtestcase is a tool which can record keypresses from a remote together
with the decoded values. Given output from another session, it can
also verify that the decoding still works as expected.
.P
In the first form irtestcase will wait for input and create log files
for it. Doing so, it also echoes received buttons on stdout. There is
no way to stop the program in a clean way, just use ctrl-C when completed.
.P
In the second form it will feed the data from the testdata file to lircd
and log the the decoded data as usually. Thus, this makes it possible to
test the output from the remote which generated the testdata.  In this
form lircd must be running with the "file" driver.
.P
The optional socket is the lircd output socket (lircd must be running). It
defaults to LIRC_SOCKET_PATH in environment, falling back to a hardcoded
default value (usually /var/run/lirc/lircd).

.SH OPTIONS

.TP 4
.B -l, --lircrc  <lircrc config file>
Log also applications strings (as ircat(1)) using lircrc type config file.

.TP 4
.B -p, --prog <program id>
When using -l/--lircrc, the program name matching the PROG = entries
in lircrc

.TP 4
.B -t, --testdata
Use data i file instead of "live" input from the remote. This can be
the durations.log file from a previous run, see FILES. It can also
be logged output from mode2(1).

.TP 4
.B -v , --version
Print version and exit.

.TP 4
.B -h , --help
Print help message.

.SH FILES
irtestcase creates files in /tmp/irtestcase (hardcoded, sorry). After a
successful run here is:
.TP 4
.B durations.log
Printable space/pulse durations in the same format as mode2(1). This file
is usable as -t/--testdata input.
.TP 4
.B codes.log
The decoded  buttons, in same format as irw(1).
.TP 4
.B app_strings.log
The application strings, as presented by ircat(1).

.SH FILES

.TP 4
.B ~/.cache/irtestcase.log
Debug output. Setting the XDG_CACHE_HOME environment variable relocates this
file to $XDG_CACHE_HOME/irtestcase.log

.SH "SEE ALSO"
The documentation for
.B lirc
is maintained as html pages. They are located under html/ in the
documentation directory.
