.TH IRW "1" "Last change: Aug 2015" "irw @version@" "User Commands"
.SH NAME
.P
\fBirw\fR - Send data from Unix domain socket to stdout
.SH SYNOPSIS
.P
\fBirw\fR [\fIsocket\fR]
.SH DESCRIPTION

irw will connect to any Unix domain socket and will print the data that it
receives to stdout. If you don't give it a socket name argument it will watch
\//var/run/lirc/lircd. Useful for debugging.
.TP
\fB\-h\fR \fI\-\-help\fR
display usage summary
.TP
\fB\-v\fR \fI\-\-version\fR
display version
.SH SIGNALS
On receiving SIGUSR1 irw makes a clean exit.
.SH "SEE ALSO"
.P
The documentation for \fBlirc\fR
is maintained as html pages. They are located under html/ in the
documentation directory.
