.TH LIRC_MAKE_DEVINPUT "1" "Last change: Oct 2015" "lirc-make-devinput @version@" "User Commands"
.SH NAME
lirc-make-devinput - create a devinput.lircd.conf for the local site.
.SH SYNOPSIS
.B lirc-make-devinput [\fIinput.h\fR]
.SH ARGUMENTS
.TP
.B input.h
Header file parsed to create the configuration file.

.SH DESCRIPTION
Reads the system header files and creates a devinput.lircd.conf which
matches the local system (i. e., the local kernel). It normally requires
that the kernel-headers package is installed.
.SH FILES
.TP
/usr/include/linux/input.h
Default system header file

.SH "SEE ALSO"
.P
The documentation for
.B lirc
is maintained as html pages. They are located under html/ in the
documentation directory.
