.TH LIRC_POSTINSTALL "1" "Last change: Sep 2017" "lirc-postinstall @version@" "User Commands"
.SH NAME
lirc-postinstall - lirc postinstall configuration
.SH SYNOPSIS
.B lirc-postinstall <\fIconfig.py\fR>
.SH ARGUMENTS
.TP
.B config.py
Normally, the lirc config.py file typically installed in
/usr/share/lirc/python-pkg/lirc/config.py. This file contains
the lirc installation paths.

.SH DESCRIPTION
\fBlirc-postinstall\fR performs various tasks which must be done either on
the target system and/or using the final installation paths.
Generated data includes driver table and external plugins documentation.

.SH ENVIRONMENT
.TP
PYTHON
Python interpreter, defaults to \fIpython3\fR
.TP
DESTDIR
Common prefix for all installation paths, typically as given to
\fImake install\fR.

.SH NOTES
This script patches some files with absolute configuration paths.
As a consequence, the installed package cannot be relocated to another
location after running \fBlirc-postinstall\fR.
