.TH MODE2 "1" "Last change: Jan 2015" "mode2 @version@" "User Commands"
.SH NAME
mode2 - shows pulse/space length or decoded input from infrared drivers

.SH SYNOPSIS
.B mode2
[\fIoptions\fR]
.SH DESCRIPTION
The main purpose of these programs is to check operation of your
home-brew LIRC receiver hardware and to see the IR waveform of the
remote controller without an expensive oscilloscope. Very useful for
debugging also in situations you just need to verify configuration.

mode2 will simply print pulse and space lengths to stdout for drivers
supporting LIRC_MODE_MODE2. For drivers supporting LIRC_MODE_LIRCCODE such
as TV-cards and the irman driver mode2 writes the decoded, integer values.

.SH OPTIONS

.TP
\fB\-h\fR \fB\-\-help\fR
display usage summary
.TP
\fB\-v\fR \fB\-\-version\fR
display version
.TP
\fB\-d\fR \fB\-\-device\fR=\fIdevice\fR
read from given device
.TP
\fB\-H\fR \fB\-\-driver\fR=\fIdriver\fR
use given driver
.TP
\fB\-m\fR \fB\-\-mode\fR
enable alternative display mode
.TP
\fB\-r\fR \fB\-\-raw\fR
access device directly

.SH RUNNING AS ROOT
In many cases mode2 needs to run as root to access devices not available
to regular users. On the other hand, running as root creates problems
such as log files owned by root, security concerns etc.
.P
In order to cope with this, mode2 by default drops root privileges
after opening the input device. This support is based on that root
permissions are acquired using sudo(1) e. g., using
.nf

        $ sudo mode2 --raw /dev/lirc0

.fi
If not using sudo, the same behaviour could be accomplished using the
SUDO_USER environment variable e. g.,
.nf

        # SUDO_USER=$LOGNAME mode2 --raw /dev/lirc0

.fi
The --keep-root option will make mode2 to keep root privileges for the
complete run.


.SH "DRIVER LOADING"
Drivers are loaded dynamically. The search path used for this is determined
by (falling priority):
.IP \- 2
The --plugindir option if available.
.IP \- 2
The 'plugindir' entry in  the [lircd] section of the lirc_options.conf file.
.IP \- 2
The environment variable LIRC_PLUGINDIR.
.IP \- 2
A hardcoded default (usually /usr/lib[64]/lirc/plugins).

.SH ENVIRONMENT
.TP 4
.B LIRC_LOGLEVEL
Determines the amount of logging information. [level] can be a symbolic
syslog level: 'error','warning, 'info', 'notice' or  'debug'. lircd
also defines three additional levels 'trace', 'trace1' and 'trace2' which
gives even more messages ('trace2' bringing the most). However, in the
log these messages are marked as 'debug'.
.IP
The level can also be an integer in the range 3 (almost no messages) to
10.


.SH FILES

.TP 4
.B ~/.cache/mode2.log
Debug output. Setting the XDG_CACHE_HOME environment variable relocates this
file to $XDG_CACHE_HOME/mode2.log

.SH "SEE ALSO"
xmode2(1)
.br
lirc_ioctl(4)
.br
lirc(4)

The documentation for
.B lirc
is maintained as html pages. They are located under html/ in the
documentation directory.
